In [139]:
import numpy as np

def get_consecutive_state(arr):
    """
    將array中連續出現5次的相同元素取出，其餘位置標為0。
    """
    mask = np.concatenate(([False], arr[:-1] != arr[1:], [False]))
    idx = np.flatnonzero(mask[1:] != mask[:-1])
    count = idx[1::2] - idx[::2]
    #max_count_idx = np.argmax(count, default=-1)
    max_count_idx = np.argmax(count) if len(count) > 0 else -1
    if max_count_idx >= 0 and count[max_count_idx] >= 5:
        state = arr[idx[max_count_idx*2]]
        return np.where(arr == state, state, 0)
    else:
        return np.zeros_like(arr)

# 示例输入
arr = np.array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 4, 4, 4, 4, 4, 4, 0, 5, 5, 5])

# 调用函数
result = get_consecutive_state(arr)

# 输出结果
print(result)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [129]:
import numpy as np

def get_consecutive_state(arr):
    """
    將array中連續出現5次的相同元素取出，其餘位置標為0。
    """
    mask = np.concatenate(([False], arr[:-1] != arr[1:], [False]))
    idx = np.flatnonzero(mask[1:] != mask[:-1])
    count = idx[1::2] - idx[::2]
    max_count = np.max(count)
    if max_count >= 5:
        state = arr[idx[np.argmax(count)*2]]
        return np.where(arr == state, state, 0)
    else:
        return np.zeros_like(arr)

# 示例输入
arr = np.array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 4, 4, 4, 4, 4, 4, 0, 5, 5, 5])

# 调用函数
result = get_consecutive_state(arr)

# 输出结果
print(result)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [124]:
arr

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 4,
       4, 4, 4, 4, 4, 0, 5, 5, 5])

In [125]:
status

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 4,
       4, 4, 4, 4, 4, 0, 5, 5, 5])

In [126]:
import numpy as np

# 创建一个示例数组，包含五个状态：1、2、3、4、5
arr = np.array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 4, 4, 4, 4, 4, 4, 0, 5, 5, 5])

# 使用卷积操作来查找连续的五个相同的状态
result = np.zeros(len(arr), dtype=int)
for i in range(1, 6):
    # 将当前状态的元素设为 1，其他状态的元素设为 0
    temp_arr = np.zeros(len(arr), dtype=int)
    temp_arr[arr == i] = 1
    
    # 使用卷积操作查找连续的五个相同的状态
    kernel = np.ones(5)
    temp_result = np.convolve(temp_arr, kernel, mode='same')
    
    # 将大于等于 5 的元素视为当前状态，其他元素视为 0
    temp_result[temp_result < 5] = 0
    temp_result[temp_result >= 5] = i
    
    # 将当前状态的结果加到总结果中
    result = result + temp_result

# 输出结果
print(result)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4.
 4. 0. 0. 0. 0. 0. 0.]


In [111]:
import numpy as np

# 创建一个示例数组，包含五个状态：1、2、3、4、5
arr = np.array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 4, 4, 4, 4, 4, 4, 0, 5, 5, 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5])

# 将五个状态的元素分别设为 1、2、3、4、5
arr_states = np.zeros((len(arr), 5), dtype=int)
for i in range(1, 6):
    arr_states[:, i-1][arr == i] = 1

# 使用卷积操作查找连续的五个相同的元素
kernel = np.ones(5)
result_states = np.apply_along_axis(lambda x: np.convolve(x, kernel, mode='same'), axis=0, arr=arr_states)

# 将大于等于 5 的元素视为当前状态，其他元素视为 0
result_states[result_states < 5] = 0




In [ ]:
tt = np.argmax(result_states, axis=1) 
tt0 = tt[tt>0] 
result_states[result_states >= 5] = tt0 +1

# 将所有状态的结果相加得到总结果
result = np.sum(result_states, axis=1)

# 输出结果
print(result)

In [51]:
import numpy as np

# 创建一个示例数组，包含五个状态：1、2、3、4、5
arr = np.array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0, 3, 3, 3, 0, 4, 4, 4, 4, 4, 4, 0, 5, 5, 5])

# 将五个状态的元素分别设为 1、2、3、4、5
arr_states = np.zeros((len(arr), 5), dtype=int)
for i in range(1, 6):
    arr_states[:, i-1][arr == i] = 1
    
# 使用卷积操作查找连续的五个相同的元素
kernel = np.ones(5)
result_states = np.apply_along_axis(lambda x: np.convolve(x, kernel, mode='same'), axis=0, arr=arr_states)
result_states

array([[1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.],
       [3., 1., 0., 0., 0.],
       [2., 2., 0., 0., 0.],
       [1., 3., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 3., 1., 0., 0.],
       [0., 2., 2., 0., 0.],
       [0., 1., 3., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 2., 2., 0.],
       [0., 0., 1., 3., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 3., 1.],
       [0., 0., 0., 2., 2.],
       [0., 0., 0., 1., 3.],
       [0., 0., 0., 0., 3.],
       [0., 0., 0., 0., 3.]])

In [14]:
# Importing necessary paackages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
import string

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score , recall_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.pipeline import Pipeline
import xgboost as xgb
seed = 4353

In [2]:
data = pd.read_csv('C:/Users/LL/Desktop/proposal injection molding/Data Test/活頁簿1.csv')
data.head()

Melt temperature  Mold temperature  time_to_fill  ZDx - Plasticizing time  \
0        106.476184            80.617         7.124                     3.16   
1        105.505000            81.362         6.968                     3.16   
2        105.505000            80.411         6.864                     4.08   
3        106.474827            81.162         6.864                     3.16   
4        106.466140            81.471         6.864                     3.22   

   ZUx - Cycle time  SKx - Closing force  SKs - Clamping force peak value  \
0             74.83           886.900000                       904.000000   
1             74.81           919.409791                       935.900000   
2             74.81           908.600000                       902.344823   
3             74.82           879.410870                       902.033653   
4             74.83           885.644260                       902.821269   

   Ms - Torque peak value current cycle  Mm - Torque mean value current cycle  \
0                                 116.9                            104.300000   
1                                 113.9                            104.900000   
2                                 120.5                            106.503496   
3                                 127.3                            104.900000   
4                                 120.5                            106.700000   

   APSs - Specific back pressure peak value  \
0                                     145.6   
1                                     145.6   
2                                     147.0   
3                                     145.6   
4                                     145.6   

   APVs - Specific injection pressure peak value  \
0                                          922.3   
1                                          930.5   
2                                          933.1   
3                                          922.3   
4                                          917.5   

   CPn - Screw position at the end of hold pressure  SVo - Shot volume  \
0                                              8.82              18.73   
1                                              8.59              18.73   
2                                              8.80              18.98   
3                                              8.85              18.73   
4                                              8.80              18.75   

   quality  
0        1  
1        1  
2        1  
3        1  
4        1

In [3]:
data.columns = data.columns.str.lower()
data.columns

Index(['melt temperature', 'mold temperature', 'time_to_fill',
       'zdx - plasticizing time', 'zux - cycle time', 'skx - closing force',
       'sks - clamping force peak value',
       'ms - torque peak value current cycle',
       'mm - torque mean value current cycle',
       'apss - specific back pressure peak value',
       'apvs - specific injection pressure peak value',
       'cpn - screw position at the end of hold pressure', 'svo - shot volume',
       'quality'],
      dtype='object')

In [4]:
data.isnull().sum()

melt temperature                                    0
mold temperature                                    0
time_to_fill                                        0
zdx - plasticizing time                             0
zux - cycle time                                    0
skx - closing force                                 0
sks - clamping force peak value                     0
ms - torque peak value current cycle                0
mm - torque mean value current cycle                0
apss - specific back pressure peak value            0
apvs - specific injection pressure peak value       0
cpn - screw position at the end of hold pressure    0
svo - shot volume                                   0
quality                                             0
dtype: int64

In [3]:
print('The train dataset contans {} rows and {} columns'.format(data.shape[0], data.shape[1]))

The train dataset contans 1451 rows and 14 columns


In [4]:
# running the function

X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:12], data['quality'], test_size=0.25, random_state= seed)

MultinomialNB

In [ ]:
# Instatiation, fitting and prediction

MNB = MultinomialNB()
MNB.fit(X_train, y_train)
predictions = MNB.predict(X_test)

In [ ]:
# Model evaluation

print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

MNB_f1 = round(f1_score(y_test, predictions, average='weighted'), 3)
MNB_accuracy = round((accuracy_score(y_test, predictions)*100),2)

print("Accuracy : " , MNB_accuracy , " %")
print("f1_score : " , MNB_f1)

RandomForestClassifier

In [ ]:
# Instatiation, fitting and predictions

from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators= 10, random_state= seed)
rfc.fit(X_train, y_train)
predictions = rfc.predict(X_test)

In [ ]:
# Model evaluation

print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

rfc_f1 = round(f1_score(y_test, predictions, average= 'weighted'), 3)
rfc_accuracy = round((accuracy_score(y_test, predictions) * 100), 2)

print("Accuracy : " , rfc_accuracy , " %")
print("f1_score : " , rfc_f1)

SVC

In [5]:
# Instatiation and fitting

from sklearn.svm import SVC
from sklearn.model_selection import KFold
svc = SVC(random_state=seed)

In [12]:
# using KFold cross validation technique
kf=  KFold(n_splits=5, random_state=seed, shuffle=True)

# Hyperparametric tuning using grid search
param_grid = [{'kernel':['rbf'],
              'gamma':[0.001, 0.0001],
              'C':[100, 1000]}]

grid = GridSearchCV(estimator=svc, param_grid=param_grid, scoring='accuracy', cv=kf)
grid.fit(X_train, y_train)

print('Estimator: ', grid.best_estimator_)
print('Best params : \n', grid.best_params_)
print('Output Classes: ', grid.classes_)
print('Training Accuracy: ', grid.best_score_)

Estimator:  SVC(C=1000, gamma=0.0001, random_state=4353)
Best params : 
 {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
Output Classes:  [1 2 3 4]
Training Accuracy:  0.9200228300849786


In [19]:
# predictions

predictions = grid.predict(X_test)

print(classification_report(y_test, predictions))

svc_f1 = round(f1_score(y_test, predictions, average='weighted'), 3)
svc_accuracy = round((accuracy_score(y_test, predictions)*100), 2)
svc_recall = round((recall_score(y_test, predictions, average='weighted')*100), 2)

print("Accuracy : " , svc_accuracy , " %")
print("f1_score : " , svc_f1)
print("recall_score : " , svc_f1)

              precision    recall  f1-score   support

           1       0.91      0.85      0.88        92
           2       0.86      0.90      0.88       103
           3       0.93      0.94      0.94        89
           4       0.95      0.95      0.95        79

    accuracy                           0.91       363
   macro avg       0.91      0.91      0.91       363
weighted avg       0.91      0.91      0.91       363

Accuracy :  90.91  %
f1_score :  0.909
recall_score :  0.909


NuSVC

In [ ]:
from sklearn.svm import NuSVC
from sklearn.model_selection import KFold
nusvc = NuSVC(random_state= seed)

In [ ]:
# using KFold cross validation technique
kf=  KFold(n_splits=5, random_state=seed, shuffle=True)

# Hyperparametric tuning using grid search
param_grid = [{'kernel':['rbf','linear','poly','sigmoid'],
              'gamma':[1e-3, 1e-4]}]

grid = GridSearchCV(estimator=nusvc, param_grid=param_grid, scoring='accuracy', cv=kf)
grid.fit(X_train, y_train)

print('Estimator: ', grid.best_estimator_)
print('Best params : \n', grid.best_params_)
print('Output Classes: ', grid.classes_)
print('Training Accuracy: ', grid.best_score_)

In [ ]:
# predictions

predictions = grid.predict(X_test)

print(classification_report(y_test, predictions))

nusvc_f1 = round(f1_score(y_test, predictions, average='weighted'), 3)
nusvc_accuracy = round((accuracy_score(y_test, predictions)*100), 2)

print("Accuracy : " , nusvc_accuracy , " %")
print("f1_score : " , nusvc_f1)

In [21]:
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state= seed)

In [22]:
from sklearn.model_selection import RandomizedSearchCV

In [23]:
n_estimators = [int(x) for x in np.linspace(start=200, stop=2000, num=10)]
max_depth = [int(x) for x in np.linspace(10, 110, num=11)]
max_depth.append(None)
learning_rate=[round(float(x),2) for x in np.linspace(start=0.01, stop=0.2, num=10)]
colsample_bytree =[round(float(x),2) for x in np.linspace(start=0.1, stop=1, num=10)]

random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth,
               'learning_rate': learning_rate,
               'colsample_bytree': colsample_bytree}
random_grid 

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'learning_rate': [0.01, 0.03, 0.05, 0.07, 0.09, 0.12, 0.14, 0.16, 0.18, 0.2],
 'colsample_bytree': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]}

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [33]:
model = XGBClassifier(random_state= seed)
model.fit(X_train, y_train)
print(); print(model)


XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=4353, reg_alpha=0, ...)


In [34]:
#Random search of parameters, using 3 fold cross validation, search across 100 different combinations, and use all available cores
xg_random = RandomizedSearchCV(estimator = model, param_distributions=random_grid,
                              n_iter=100, cv=3, verbose=2, random_state=seed, n_jobs=-1)

xg_random.fit(X_train,y_train)
xg_random.best_params_

Fitting 3 folds for each of 100 candidates, totalling 300 fits


{'n_estimators': 1000,
 'max_depth': 20,
 'learning_rate': 0.09,
 'colsample_bytree': 0.4}

In [37]:
random_grid

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'learning_rate': [0.01, 0.03, 0.05, 0.07, 0.09, 0.12, 0.14, 0.16, 0.18, 0.2],
 'colsample_bytree': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]}

In [41]:
print('Estimator: ', xg_random.best_estimator_)
print('Best params : \n', xg_random.best_params_)
print('Output Classes: ', xg_random.classes_)
print('Training Accuracy: ', xg_random.best_score_)

Estimator:  XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.4,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.09, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=20, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=1000,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=4353, reg_alpha=0, ...)
Best params : 
 {'n_estimators': 1000, 'max_depth': 20, 'learning_rate': 0.09, 'colsample_bytree': 0.4}
Output Classes:  [0 1 2 3]
Training Accuracy:  0.9420853436423502
